spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
---
spring:
  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false