spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        time_zone: Asia/Seoul
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    auth: true
    starttls:
      enable: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESSKEY}
      secretKey: ${AWS_S3_SECRETKEY}
    s3:
      bucket: codestates-39-team17-image
      dir: CCoMo
    region:
      static: ap-northeast-2
    stack:
      auto: false