spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mocco?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: team60
    password: team60_1234
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        time_zone: Asia/Seoul
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print