spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false